#!/usr/bin/env python3
# Copyright 2026 The SlipX Authors
# SPDX-License-Identifier: Apache-2.0

"""Generate the track geometry that ships with SlipX.

SlipX redistributes no third-party track geometry (ADR-0035): every public
centreline set in this format is copyleft, and the F1TENTH maps for real
venues carry no licence at all. What ships instead is this script and what it
produces, which is Apache-2.0 like the rest of the tree, and a converter for
turning somebody else's track into a SlipX one on their own machine.

The track produced here is a stadium: two straights joined by two semicircular
ends. It is not a real venue and the manifest says so. It is shaped this way
because the things that run against it need different things from it, and a
circle gives only one of them: a lap counter needs it closed, a pure pursuit
controller needs curvature that changes, and a wall follower needs a straight
long enough to settle on before the next corner arrives.

Every dimension below is exact, so every property of the output can be
asserted rather than eyeballed, which is what the checks at the bottom do.

Standard library only, like every other generator in this repository.

Run:  python3 examples/tracks/make_tracks.py
"""

from __future__ import annotations

import math
from pathlib import Path

HERE = Path(__file__).resolve().parent

# The stadium, in metres. A 1/10-scale car on a 34.85 m lap at a plausible
# 4 m/s runs about a nine-second lap, which is the right order for a sports
# hall and short enough that a CI lap test is not a CI timeout.
STRAIGHT_M = 8.0        # length of each straight
RADIUS_M = 3.0          # centreline radius of each end
HALF_WIDTH_M = 0.75     # drivable width each side of the centreline

#: Distance between centreline samples. Small enough that the polyline's
#: chord length is within a millimetre of the true arc length around the ends,
#: which the checks below assert rather than assume.
SPACING_M = 0.10

LAP_M = 2.0 * STRAIGHT_M + 2.0 * math.pi * RADIUS_M


def point_at(s: float) -> tuple[float, float]:
    """The centreline point at arc length ``s`` from the start.

    Anticlockwise, which is positive yaw under ISO 8855, starting at the
    beginning of the bottom straight. The four segments in order are: bottom
    straight, right end, top straight, left end.
    """
    half = STRAIGHT_M / 2.0
    end = math.pi * RADIUS_M

    if s < STRAIGHT_M:                                    # bottom straight
        return (-half + s, -RADIUS_M)
    s -= STRAIGHT_M

    if s < end:                                           # right end
        theta = -math.pi / 2.0 + s / RADIUS_M
        return (half + RADIUS_M * math.cos(theta), RADIUS_M * math.sin(theta))
    s -= end

    if s < STRAIGHT_M:                                    # top straight
        return (half - s, RADIUS_M)
    s -= STRAIGHT_M

    theta = math.pi / 2.0 + s / RADIUS_M                  # left end
    return (-half + RADIUS_M * math.cos(theta), RADIUS_M * math.sin(theta))


def centreline() -> list[tuple[float, float]]:
    """Samples around one lap, the closing point excluded.

    The last point does not repeat the first. The manifest declares the track
    closed and the loader derives the closing chord from that, so writing the
    start twice would be a zero-length segment at the join.
    """
    count = round(LAP_M / SPACING_M)
    return [point_at(index * LAP_M / count) for index in range(count)]


def render(points: list[tuple[float, float]]) -> str:
    lines = [
        "# SlipX generated track: a stadium, two 8 m straights and two 3 m ends.",
        "# NOT a real venue. Generated by examples/tracks/make_tracks.py.",
        "# Apache-2.0, like the rest of this repository.",
        "#",
        "# Four columns, the form used by the TUM racetrack database and the",
        "# F1TENTH set derived from it. Arc length is derived by the loader,",
        "# not read, so there is no column for it.",
        "# x_m,y_m,w_tr_right_m,w_tr_left_m",
    ]
    for x, y in points:
        lines.append(
            f"{x:.6f},{y:.6f},{HALF_WIDTH_M:.6f},{HALF_WIDTH_M:.6f}"
        )
    return "\n".join(lines) + "\n"


def check(points: list[tuple[float, float]]) -> None:
    """Assert the geometry rather than looking at it.

    A generated figure that is subtly wrong is worse than no figure, because
    everything downstream then agrees with it.
    """
    half = STRAIGHT_M / 2.0

    # Every point is on the shape: on a straight, or on one of the two ends.
    for x, y in points:
        if -half <= x <= half:
            assert abs(abs(y) - RADIUS_M) < 1e-9, f"({x}, {y}) is off a straight"
        else:
            centre = half if x > 0 else -half
            radius = math.hypot(x - centre, y)
            assert abs(radius - RADIUS_M) < 1e-9, f"({x}, {y}) is off an end"

    # The samples are uniform in arc length by construction. The distances
    # between them are not quite uniform, and expecting them to be is the easy
    # mistake here: a chord across an arc is shorter than the arc it spans, so
    # the steps around the ends come out a few microns under the steps along
    # the straights. What is asserted is that no chord exceeds its arc, which
    # would mean the sampling was wrong rather than merely discrete, and that
    # the shortfall stays negligible.
    nominal = LAP_M / len(points)
    steps = [
        math.hypot(points[i][0] - points[i - 1][0], points[i][1] - points[i - 1][1])
        for i in range(1, len(points))
    ]
    assert min(steps) > 0.0, "two consecutive points coincide"
    assert max(steps) <= nominal + 1e-12, "a chord is longer than its arc"
    assert min(steps) > nominal - 1e-5, "the sampling is too coarse"

    # The polyline is shorter than the true lap, because a chord cuts the
    # corner off an arc. At this spacing the deficit is under a millimetre,
    # and the assertion is what keeps it that way if SPACING_M is ever raised.
    closing = math.hypot(
        points[0][0] - points[-1][0], points[0][1] - points[-1][1]
    )
    polyline = sum(steps) + closing
    assert 0.0 <= LAP_M - polyline < 1e-3, (
        f"polyline is {polyline:.6f} m against a true lap of {LAP_M:.6f} m; "
        f"raise the sampling rate"
    )

    # The start is the start of the bottom straight, travelling anticlockwise.
    assert points[0] == (-half, -RADIUS_M), points[0]
    assert points[1][0] > points[0][0], "the first segment runs the wrong way"


def main() -> int:
    points = centreline()
    check(points)

    target = HERE / "paddock_stadium" / "centreline.csv"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(points), encoding="utf-8", newline="\n")

    print(f"{target.relative_to(HERE.parent.parent)}: {len(points)} points, "
          f"lap {LAP_M:.3f} m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
