// Copyright 2026 The SlipX Authors
// SPDX-License-Identifier: Apache-2.0
//
// The track: a centreline plus a manifest, and the surface-to-tyre pairing
// that ADR-0010 exists to protect.
//
// Every field the manifest carries is one somebody could leave out, and
// leaving any of them out is a claim about a real place. So each has a case
// here, and each case reads the message, because a refusal that does not name
// what is wrong is barely better than a crash.

#include <gtest/gtest.h>

#include <stdexcept>
#include <string>
#include <vector>

#include "slipx/scene/centreline.hpp"
#include "slipx/scene/track.hpp"

namespace {

using slipx::scene::Centreline;
using slipx::scene::Track;
using slipx::scene::TrackManifest;
using slipx::scene::TyrePair;

template <typename F>
std::string refusal_from(F&& call) {
  try {
    call();
  } catch (const std::invalid_argument& e) {
    return e.what();
  }
  return std::string();
}

bool mentions(const std::string& haystack, const std::string& needle) {
  return haystack.find(needle) != std::string::npos;
}

// A unit square, so the open length is 3 and the closing chord is 1.
Centreline square() {
  return Centreline::from_csv(
      "0.0,0.0,1.0,1.0\n"
      "1.0,0.0,1.0,1.0\n"
      "1.0,1.0,1.0,1.0\n"
      "0.0,1.0,1.0,1.0\n",
      "square/centreline.csv");
}

TrackManifest carpet_manifest() {
  TrackManifest manifest;
  manifest.name = "square";
  manifest.surface = "carpet";
  manifest.closed = true;
  manifest.geometry_source = "generated by tools/make_track.py";
  manifest.geometry_licence = "Apache-2.0";
  manifest.provenance_label = "provisional";
  return manifest;
}

std::vector<TyrePair> carpet_tyres() {
  return {{"sponge", "carpet"}, {"sponge", "carpet"}};
}

TEST(Track, BuildsWhenEveryTyreIsForTheDeclaredSurface) {
  const Track track = Track::build(square(), carpet_manifest(), carpet_tyres());

  EXPECT_EQ(track.name(), "square");
  EXPECT_EQ(track.surface(), "carpet");
  EXPECT_TRUE(track.is_closed());
  EXPECT_EQ(track.centreline().size(), 4u);
  EXPECT_EQ(track.tyres().size(), 2u);
}

// Whether the closing chord counts is the manifest's answer, not the
// geometry's, and the two answers differ by exactly that chord.
TEST(Track, LengthIncludesTheClosingChordOnlyWhenTheTrackIsClosed) {
  const Track closed = Track::build(square(), carpet_manifest(), carpet_tyres());
  EXPECT_DOUBLE_EQ(closed.length(), 4.0);

  TrackManifest open_manifest = carpet_manifest();
  open_manifest.closed = false;
  const Track open = Track::build(square(), open_manifest, carpet_tyres());
  EXPECT_DOUBLE_EQ(open.length(), 3.0);
}

TEST(Track, RefusesATyreForAnotherSurface) {
  const std::string message = refusal_from([] {
    Track::build(square(), carpet_manifest(), {{"slick", "asphalt"}});
  });
  EXPECT_TRUE(mentions(message, "square")) << message;
  EXPECT_TRUE(mentions(message, "carpet")) << message;
  EXPECT_TRUE(mentions(message, "asphalt")) << message;
  EXPECT_TRUE(mentions(message, "slick")) << message;
}

// The check is over every tyre, not the first match. A car whose axles are on
// different surfaces is exactly the mistake a search for one match waves
// through, and it is the mistake ADR-0010 was written about.
TEST(Track, RefusesWhenOnlyOneAxleIsForTheDeclaredSurface) {
  const std::string message = refusal_from([] {
    Track::build(square(), carpet_manifest(),
                 {{"sponge", "carpet"}, {"slick", "asphalt"}});
  });
  EXPECT_TRUE(mentions(message, "asphalt")) << message;
  // The refusal lists what it was offered, so the reader can see the pair
  // that matched as well as the one that did not.
  EXPECT_TRUE(mentions(message, "(sponge, carpet)")) << message;
}

// Surface identifiers match exactly. Folding case here would be a silent
// normalisation of the one string that decides which measurement applies, and
// two spellings of a surface in a registry is a problem to fix at the point
// of contribution rather than paper over at the point of use.
TEST(Track, MatchesTheSurfaceIdentifierExactly) {
  const std::string message = refusal_from([] {
    Track::build(square(), carpet_manifest(), {{"sponge", "Carpet"}});
  });
  EXPECT_TRUE(mentions(message, "Carpet")) << message;
}

TEST(Track, RefusesAnEmptyTyreList) {
  const std::string message = refusal_from(
      [] { Track::build(square(), carpet_manifest(), {}); });
  EXPECT_TRUE(mentions(message, "carpet")) << message;
  EXPECT_TRUE(mentions(message, "no tyres")) << message;
}

TEST(Track, RefusesAManifestWithNoName) {
  TrackManifest manifest = carpet_manifest();
  manifest.name.clear();
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "no name")) << message;
}

TEST(Track, RefusesAManifestWithNoSurface) {
  TrackManifest manifest = carpet_manifest();
  manifest.surface.clear();
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "no surface")) << message;
  EXPECT_TRUE(mentions(message, "square")) << message;
}

// Not inferred from the geometry, and not defaulted to either answer.
TEST(Track, RefusesAManifestThatDoesNotSayWhetherTheTrackCloses) {
  TrackManifest manifest = carpet_manifest();
  manifest.closed.reset();
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "closes")) << message;
}

// Refused, not dropped. Nothing consumes banking yet, and a number that is
// silently ignored is worse than one that is absent.
TEST(Track, RefusesADeclaredBanking) {
  TrackManifest manifest = carpet_manifest();
  manifest.banking_rad = 0.05;
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "banking")) << message;
}

// Including zero. A flat track is a measurement, not an absence.
TEST(Track, RefusesADeclaredBankingOfZero) {
  TrackManifest manifest = carpet_manifest();
  manifest.banking_rad = 0.0;
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "banking")) << message;
}

TEST(Track, RefusesAProvenanceLabelOutsideTheThree) {
  for (const char* label : {"", "validated", "generated", "surveyed"}) {
    TrackManifest manifest = carpet_manifest();
    manifest.provenance_label = label;
    const std::string message = refusal_from([&manifest] {
      Track::build(square(), manifest, carpet_tyres());
    });
    EXPECT_TRUE(mentions(message, "measured, identified, provisional"))
        << label << ": " << message;
  }
}

TEST(Track, AcceptsEachOfTheThreeProvenanceLabels) {
  for (const char* label : {"measured", "identified", "provisional"}) {
    TrackManifest manifest = carpet_manifest();
    manifest.provenance_label = label;
    EXPECT_NO_THROW(Track::build(square(), manifest, carpet_tyres())) << label;
  }
}

TEST(Track, RefusesGeometryWithNoStatedSource) {
  TrackManifest manifest = carpet_manifest();
  manifest.geometry_source.clear();
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "where its geometry came from")) << message;
}

// SlipX ships no third-party geometry, so whatever a user converted into
// place arrived under somebody's terms, and the manifest says which.
TEST(Track, RefusesGeometryWithNoStatedLicence) {
  TrackManifest manifest = carpet_manifest();
  manifest.geometry_licence.clear();
  const std::string message = refusal_from([&manifest] {
    Track::build(square(), manifest, carpet_tyres());
  });
  EXPECT_TRUE(mentions(message, "licence")) << message;
}

// --------------------------------------------------------- the shipped track
//
// The generated stadium in examples/tracks. Its dimensions are exact by
// construction, which is what makes them worth asserting here: two 8 m
// straights and two semicircular ends of 3 m radius, so one lap is
// 2*8 + 2*pi*3 = 34.8496 m, and the polyline is a hair under that because a
// chord cuts the corner off an arc.

TEST(ShippedTrack, LoadsAndMeasuresTheLapItClaims) {
  const Centreline geometry =
      Centreline::from_file(std::string(SLIPX_EXAMPLE_TRACK_DIR) +
                            "/centreline.csv");

  TrackManifest manifest;
  manifest.name = "paddock_stadium";
  manifest.surface = "carpet";
  manifest.closed = true;
  manifest.geometry_source = "examples/tracks/make_tracks.py";
  manifest.geometry_licence = "Apache-2.0";
  manifest.provenance_label = "provisional";

  const Track track =
      Track::build(geometry, manifest, {{"sponge", "carpet"}});

  const double lap = 2.0 * 8.0 + 2.0 * 3.14159265358979323846 * 3.0;
  EXPECT_TRUE(track.is_closed());
  EXPECT_NEAR(track.length(), lap, 1e-3);
  EXPECT_LT(track.length(), lap) << "a chord cannot be longer than its arc";

  // The widths are 0.75 m each side, which is the 1.5 m the manifest
  // describes, and they are read right before left.
  for (const auto& point : track.centreline().points()) {
    EXPECT_DOUBLE_EQ(point.w_left, 0.75);
    EXPECT_DOUBLE_EQ(point.w_right, 0.75);
  }
}

// The car that ships and the track that ship agree, so somebody following the
// README meets none of the refusals above.
TEST(ShippedTrack, TakesTheReferenceCarsTyres) {
  const Centreline geometry =
      Centreline::from_file(std::string(SLIPX_EXAMPLE_TRACK_DIR) +
                            "/centreline.csv");

  TrackManifest manifest = carpet_manifest();
  manifest.name = "paddock_stadium";

  EXPECT_NO_THROW(Track::build(geometry, manifest,
                               {{"sponge", "carpet"}, {"sponge", "carpet"}}));
}

}  // namespace
